include: all_lint_rules.yaml
analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    included_file_warning: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
