targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
    builders:
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/src/interface/responsive_view/types.dart
